FIx
Warning:
require(/home/grapplerulrich/universaltheme.tk/wp-content/themes/universal-beta/inc/jetpack.php)
[function.require]: failed to open stream: No such file or directory in
/home/grapplerulrich/universaltheme.tk/wp-content/themes/universal-beta/functions.php
on line 241

Fatal error: require() [function.require]: Failed opening required
'/home/grapplerulrich/universaltheme.tk/wp-content/themes/universal-beta/inc/jetpack.php'
(include_path='.:/usr/local/lib/php:/usr/local/php5/lib/pear') in
/home/grapplerulrich/universaltheme.tk/wp-content/themes/universal-beta/functions.php
on line 241